name: ${name}
version: ${version}
api-version: ${plugin.apiVersion}
author: ${plugin.author}
website: ${plugin.website}
main: ${plugin.main}

commands:
    0:
        description: Change your Gamemode with this shorthand to Survival
        usage: /0
    1:
        description: Change your Gamemode with this shorthand to Creative
        usage: /1
    2:
        description: Change your Gamemode with this shorthand to Adventure
        usage: /2
    3:
        description: Change your Gamemode with this shorthand to Spectator
        usage: /3
    purse:
        description: Shows Total of Coins in Purse 
        usage: /purse
    fly:
        description: Toggle your fly mode
        usage: /fly
    craft:
        description: Open Craftingbench protable
        usage: /craft
    cookie:
        description: Share a Cookie (with your best friend)
        usage: /cookie
    sun:
        description: Change the Weather (Tutti Frutti Summer Love)
        usage: /sun
    rain:
        description: Change the Weather (Rainy Days and Mondays)
        usage: /rain
    storm:
        description: Change the Weather (Call it stormy Monday)
        usage: /storm
    spawn:
        description: Teleport to the World Spawn
        usage: /spawn
    day:
        description: Change time to Day
        usage: /day
    night:
        description: Change time to Night
        usage: /night
    enderchest:
        description: Open the Enderchest
        usage: /enderchest
    inv:
        description: Open the Inventory
        usage: /inv
    setGroup:
        description: Set Player Group 
        usage: /setGroup
    nick:
        description: Set Player Name 
        usage: /nick
    suicide:
        description: Kill yourself
        usage: /suicide
    more:
        description: Give yourself more of the item in your Mainhand
        usage: /more
    repair:
        description: Repair your Tool in the Mainhand
        usage: /repair
    home:
        description: Teleport to your Bedspawn
        usage: /home
    god:
        description: toogle god mode
        usage: /god
    admin:
        description: shows options for admins
        usage: /admin
    head:
        description: gives you a player head
        usage: /head
    vanish:
        description: vanishes player
        usage: /vanish
        aliases: v
    heal:
        description: heal player
        usage: /heal
    afk:
        description: set player afk
        usage: /afk
    msg:
        description: message other player
        usage: /msg
    r:
        description: reply other player
        usage: /r
    title:
        description: spawn title for player
        usage: /title
    where:
        description: shows player location
        usage: /where
    print:
        description: sends message from player or commandblock
        usage: /print
    broadcast:
        description: sends message to all players via chat or title
        usage: /broadcast
    rename:
        description: rename item in hand
        usage: /rename
    poke:
        description: Pokes a Player
        usage: /poke <name>
    speed:
        description: set either fly or walk speed of the player
        usage: /speed
    world:
        description: shows worlds, world management and tp
        usage: /world
    rollback:
        description: rollbacks changes in the world by the player x
        usage: /rollback
    ZAQmNCRXEdwSGU7DvEcXTbBkp2qEaCSSNkQcMhL3m7KSDtmXWaxtbYCaQCFBR96fj:            
        description: not a command
        usage: /ZAQmNCRXEdwSGU7DvEcXTbBkp2qEaCSSNkQcMhL3m7KSDtmXWaxtbYCaQCFBR96fj
    gamerules:
        description: shows gamerules from world the sender is in
        usage: /gamerules
    protect:
        description: protects Blocks, Modify Protections add Flags etc 
        usage: /protect
    sign:
        description: edit a Sign or copy and paste its contents 
        usage: /sign
    bags:
        description: Opens the Bags GUI 
        usage: /bags
    sudo:
        description: Linux like sudo
        usage: /sudo
    exit:
        description: Linux like exit 
        usage: /exit
    teleport:
        description: Telport Player
        usage: /teleport
    back:
        description: Teleports to last location
        usage: /back
    warp:
        description: Warps Player
        usage: /warp
    marry:
        description: Marry Player
        usage: /marry

