/**
 * Author:  rellu
 * Created: 12.02.2023
 */


INSERT INTO `rellu_essentials`.`protection_locks` (`id`, `created`, `createdby`, `value`) VALUES 
( 1, now(), 1, 'OAK_SIGN'),
( 2, now(), 1, 'SPRUCE_SIGN'),
( 3, now(), 1, 'BIRCH_SIGN'),
( 4, now(), 1, 'JUNGLE_SIGN'),
( 5, now(), 1, 'ACACIA_SIGN'),
( 6, now(), 1, 'DARK_OAK_SIGN'),
( 7, now(), 1, 'MANGROVE_SIGN'),
( 8, now(), 1, 'CRIMSON_SIGN'),
( 9, now(), 1, 'WARPED_SIGN'),
(10, now(), 1, 'OAK_WALL_SIGN'),
(11, now(), 1, 'SPRUCE_WALL_SIGN'),
(12, now(), 1, 'BIRCH_WALL_SIGN'),
(13, now(), 1, 'JUNGLE_WALL_SIGN'),
(14, now(), 1, 'ACACIA_WALL_SIGN'),
(15, now(), 1, 'DARK_OAK_WALL_SIGN'),
(16, now(), 1, 'MANGROVE_WALL_SIGN'),
(17, now(), 1, 'CRIMSON_WALL_SIGN'),
(18, now(), 1, 'WARPED_WALL_SIGN'),
(19, now(), 1, 'OAK_WALL_HANGING_SIGN'),
(20, now(), 1, 'SPRUCE_WALL_HANGING_SIGN'),
(21, now(), 1, 'BIRCH_WALL_HANGING_SIGN'),
(22, now(), 1, 'JUNGLE_WALL_HANGING_SIGN'),
(23, now(), 1, 'ACACIA_WALL_HANGING_SIGN'),
(24, now(), 1, 'DARK_OAK_WALL_HANGING_SIGN'),
(25, now(), 1, 'MANGROVE_WALL_HANGING_SIGN'),
(26, now(), 1, 'CRIMSON_WALL_HANGING_SIGN'),
(27, now(), 1, 'WARPED_WALL_HANGING_SIGN'),
(28, now(), 1, 'OAK_HANGING_SIGN'),
(29, now(), 1, 'SPRUCE_HANGING_SIGN'),
(30, now(), 1, 'BIRCH_HANGING_SIGN'),
(31, now(), 1, 'JUNGLE_HANGING_SIGN'),
(32, now(), 1, 'ACACIA_HANGING_SIGN'),
(33, now(), 1, 'DARK_OAK_HANGING_SIGN'),
(34, now(), 1, 'MANGROVE_HANGING_SIGN'),
(35, now(), 1, 'CRIMSON_HANGING_SIGN'),
(36, now(), 1, 'WARPED_HANGING_SIGN'),
(37, now(), 1, 'OAK_TRAPDOOR'),
(38, now(), 1, 'SPRUCE_TRAPDOOR'),
(39, now(), 1, 'BIRCH_TRAPDOOR'),
(40, now(), 1, 'JUNGLE_TRAPDOOR'),
(41, now(), 1, 'ACACIA_TRAPDOOR'),
(42, now(), 1, 'DARK_OAK_TRAPDOOR'),
(43, now(), 1, 'MANGROVE_TRAPDOOR'),
(44, now(), 1, 'CRIMSON_TRAPDOOR'),
(45, now(), 1, 'WARPED_TRAPDOOR'),
(46, now(), 1, 'IRON_TRAPDOOR'),
(47, now(), 1, 'OAK_DOOR'),
(48, now(), 1, 'SPRUCE_DOOR'),
(49, now(), 1, 'BIRCH_DOOR'),
(50, now(), 1, 'JUNGLE_DOOR'),
(51, now(), 1, 'ACACIA_DOOR'),
(52, now(), 1, 'DARK_OAK_DOOR'),
(53, now(), 1, 'MANGROVE_DOOR'),
(54, now(), 1, 'CRIMSON_DOOR'),
(55, now(), 1, 'WARPED_DOOR'),
(56, now(), 1, 'IRON_DOOR'),
(57, now(), 1, 'OAK_FENCE_GATE'),
(58, now(), 1, 'SPRUCE_FENCE_GATE'),
(59, now(), 1, 'BIRCH_FENCE_GATE'),
(60, now(), 1, 'JUNGLE_FENCE_GATE'),
(61, now(), 1, 'ACACIA_FENCE_GATE'),
(62, now(), 1, 'DARK_OAK_FENCE_GATE'),
(63, now(), 1, 'MANGROVE_FENCE_GATE'),
(64, now(), 1, 'CRIMSON_FENCE_GATE'),
(65, now(), 1, 'WARPED_FENCE_GATE'),
(66, now(), 1, 'FURNACE'),
(67, now(), 1, 'BLAST_FURNACE'),
(68, now(), 1, 'SMOKER'),
(69, now(), 1, 'LECTERN'),
(70, now(), 1, 'CHEST'),
(71, now(), 1, 'TRAPPED_CHEST'),
(72, now(), 1, 'SHULKER_BOX'),
(73, now(), 1, 'WHITE_SHULKER_BOX'),
(74, now(), 1, 'LIGHT_GRAY_SHULKER_BOX'),
(75, now(), 1, 'GRAY_SHULKER_BOX'),
(76, now(), 1, 'BLACK_SHULKER_BOX'),
(77, now(), 1, 'BROWN_SHULKER_BOX'),
(78, now(), 1, 'RED_SHULKER_BOX'),
(79, now(), 1, 'ORANGE_SHULKER_BOX'),
(80, now(), 1, 'YELLOW_SHULKER_BOX'),
(81, now(), 1, 'LIME_SHULKER_BOX'),
(82, now(), 1, 'GREEN_SHULKER_BOX'),
(83, now(), 1, 'CYAN_SHULKER_BOX'),
(84, now(), 1, 'LIGHT_BLUE_SHULKER_BOX'),
(85, now(), 1, 'BLUE_SHULKER_BOX'),
(86, now(), 1, 'PURPLE_SHULKER_BOX'),
(87, now(), 1, 'MAGENTA_SHULKER_BOX'),
(88, now(), 1, 'PINK_SHULKER_BOX'),
(89, now(), 1, 'ITEM_FRAME'),
(90, now(), 1, 'JUKEBOX'),
(91, now(), 1, 'CAULDRON'),
(92, now(), 1, 'ENCHANTING_TABLE'),
(93, now(), 1, 'BEACON'),
(94, now(), 1, 'LODESTONE'),
(95, now(), 1, 'COMPOSTER'),
(96, now(), 1, 'BARREL'),
(97, now(), 1, 'LEVER'),
(98, now(), 1, 'ANVIL');