package de.relluem94.minecraft.server.spigot.essentials.constants;

public interface Constants {
    
    /* ******************************************************************************* */
    /*                               PLUGIN   STUFF                                    */
    /* ******************************************************************************* */

    String PLUGIN_EOL = System.lineSeparator();

    String PLUGIN_COLOR_COMMAND = "§f";
    String PLUGIN_COLOR_COMMAND_NAME = "§b";
    String PLUGIN_COLOR_COMMAND_ARG = "§b";
    String PLUGIN_COLOR_MESSAGE = "§f";
    String PLUGIN_COLOR_CONSOLE = "§c";
    String PLUGIN_COLOR_COMMAND_BLOCK = "§8";
    String PLUGIN_COLOR_MONEY = "§6"; 
    String PLUGIN_COLOR_BROADCAST = "§5";
    String PLUGIN_COLOR_MESSAGE_SPACER = "§7";
    String PLUGIN_COLOR_RESET = "§r";
    String PLUGIN_COLOR_LOGO_RELLU = "§8";
    String PLUGIN_COLOR_LOGO_ESSENTIALS = "§c";
    String PLUGIN_COLOR_POSITIVE = "§a";
    String PLUGIN_COLOR_NEGATIVE = "§c";
    String PLUGIN_COLOR_NEUTRAL = "§6";
    

    String PLUGIN_NAME_RELLU = "Rellu";
    String PLUGIN_NAME_ESSENTIALS = "Essentials";
    String PLUGIN_NAME_INITIAL_RELLU = "R";
    String PLUGIN_NAME_INITIAL_ESSENTIALS = "E";
    String PLUGIN_NAME_SHORT = PLUGIN_COLOR_LOGO_RELLU + PLUGIN_NAME_INITIAL_RELLU + PLUGIN_COLOR_LOGO_ESSENTIALS + PLUGIN_NAME_INITIAL_ESSENTIALS + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_NAME_PREFIX = PLUGIN_COLOR_LOGO_RELLU + PLUGIN_NAME_RELLU + PLUGIN_COLOR_LOGO_ESSENTIALS + PLUGIN_NAME_ESSENTIALS + PLUGIN_COLOR_RESET + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_NAME_CONSOLE = PLUGIN_COLOR_MESSAGE + "[" + PLUGIN_NAME_PREFIX + PLUGIN_COLOR_MESSAGE + "] ";
    String PLUGIN_NAME_BROADCAST = PLUGIN_COLOR_BROADCAST + "Broadcast";
    String PLUGIN_NAME_CHAT_CONSOLE = PLUGIN_COLOR_CONSOLE + "Console";
    String PLUGIN_NAME_MONEY = PLUGIN_COLOR_MONEY + "Coins" + PLUGIN_COLOR_MESSAGE; 

    String PLUGIN_WORLD_LOBBY = "lobby";
    String PLUGIN_WORLD_WORLD = "world";
    String PLUGIN_WORLD_WORLD_NETHER = "world_nether";
    String PLUGIN_WORLD_WORLD_THE_END = "world_the_end";

    String PLUGIN_FORMS_SPACER_CHANNEL = " >> " + PLUGIN_COLOR_COMMAND;
    String PLUGIN_FORMS_SPACER_MESSAGE = PLUGIN_COLOR_MESSAGE_SPACER + " >> " + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_FORMS_BORDER = "<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>";
    String PLUGIN_FORMS_WHITESPACE_SHORT = "    ";
    String PLUGIN_FORMS_COMMAND_PREFIX = PLUGIN_NAME_PREFIX + PLUGIN_FORMS_SPACER_MESSAGE + PLUGIN_COLOR_COMMAND;

    String PLUGIN_SYMBOL_HEAVY_CHECK_MARK = PLUGIN_COLOR_POSITIVE + "✔ ";
    String PLUGIN_SYMBOL_BLACK_LARGE_CIRCLE = PLUGIN_COLOR_NEUTRAL + "⬤ ";
    String PLUGIN_SYMBOL_HEAVY_MULTIPLICATION_X = PLUGIN_COLOR_NEGATIVE + "✖ ";
    String PLUGIN_SYMBOL_RIGHT_POINTING_ANGLE_BRACKET = PLUGIN_COLOR_POSITIVE + "〉";
    String PLUGIN_SYMBOL_LEFT_POINTING_ANGLE_BRACKET = PLUGIN_COLOR_NEGATIVE + "〈";
    String PLUGIN_SYMBOL_CROSS_MARK = PLUGIN_COLOR_NEGATIVE + "❌";
    String PLUGIN_SYMBOL_BLACK_FOUR_POINTED_STAR = PLUGIN_COLOR_POSITIVE + "✦";
    String PLUGIN_SYMBOL_HEART = PLUGIN_COLOR_NEGATIVE + "♥";
    // ❌ Cross Mark (U+274C)
    // ✦ Black Four Pointed Star (U+2726)

    String PLUGIN_SIGN_NAME = PLUGIN_COLOR_MESSAGE + "[" + PLUGIN_NAME_SHORT + "]";
    String PLUGIN_SIGN_CLICK = PLUGIN_COLOR_MESSAGE + "[Click here]";
    
    String PLUGIN_MANAGER_START_MESSAGE = "starts configuring ...";
    String PLUGIN_MANAGER_STOP_MESSAGE = "shutdown();";
    String PLUGIN_MANAGER_START_TIME_MESSAGE = "wurde in %s ms gestartet!";
    String PLUGIN_MANAGER_REGISTER_SKILLS = "Registriere Skills!";
    String PLUGIN_MANAGER_SKILLS_REGISTERED = "Skills erfolgreich registriert!";
    String PLUGIN_MANAGER_LOADING_CONFIGS = "Configs werden geladen!";
    String PLUGIN_MANAGER_CONFIGS_LOADED = "Configs sind geladen!";
    String PLUGIN_MANAGER_REGISTER_EVENTS = "Registriere Events!";
    String PLUGIN_MANAGER_EVENTS_REGISTERED = "%s Events erfolgreich registriert!";
    String PLUGIN_MANAGER_REGISTER_RECIPE = "Registriere Rezepte!";
    String PLUGIN_MANAGER_RECIPE_REGISTERED = "%s Rezepte erfolgreich registriert!";
    String PLUGIN_MANAGER_REGISTER_COMMANDS = "Registriere Befehle!";
    String PLUGIN_MANAGER_COMMANDS_REGISTERED = "%s Befehle erfolgreich registriert!";
    String PLUGIN_MANAGER_REGISTER_AUTOSAVE = "Registriere Auto Save!";
    String PLUGIN_MANAGER_AUTOSAVE_REGISTERED = "Auto Save erfolgreich registriert!";

    String PLUGIN_INTERNAL_UTILITY_CLASS = "This is a Utility Class";

    String PLUGIN_FOLDER_MKDIR_ERROR = "Couldn't create the Plugin Folder";

    

    /* ******************************************************************************* */
    /*                              COMMAND   STUFF                                    */
    /* ******************************************************************************* */
    String PLUGIN_COMMAND_FLYMODE = PLUGIN_FORMS_COMMAND_PREFIX + "Der Flugmodus von %s" + PLUGIN_COLOR_COMMAND + " wurde " + PLUGIN_COLOR_COMMAND_ARG + "%s!";
    String PLUGIN_COMMAND_FLYMODE_ACTIVATED = "aktiviert";
    String PLUGIN_COMMAND_FLYMODE_DEACTIVATED = "deaktiviert";

    String PLUGIN_COMMAND_NAME_GAME_MODE_0_NAME = "Survival";
    String PLUGIN_COMMAND_NAME_GAME_MODE_1_NAME = "Creative";
    String PLUGIN_COMMAND_NAME_GAME_MODE_2_NAME = "Adventure";
    String PLUGIN_COMMAND_NAME_GAME_MODE_3_NAME = "Spectator";

    String PLUGIN_COMMAND_ADMIN_PING = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast ein Ping von " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "ms!";
    String PLUGIN_COMMAND_ADMIN_PING_OTHER = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " hast ein Ping von " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "ms!";
    String PLUGIN_COMMAND_ADMIN_PING_OTHER_NOT_FOUND  = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "wurde nicht gefunden";

    String PLUGIN_COMMAND_CRAFTINGBENCH = PLUGIN_FORMS_COMMAND_PREFIX + "Die Werkbank von %s" + PLUGIN_COLOR_COMMAND + " wurde geöffnet!";

    String PLUGIN_COMMAND_COOKIES = PLUGIN_FORMS_COMMAND_PREFIX + "Ein Keks für dich, %s";
    String PLUGIN_COMMAND_COOKIES_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast %s " + PLUGIN_COLOR_COMMAND + "ein Keks geschenkt!";
    String PLUGIN_COMMAND_COOKIES_LORE_1 = PLUGIN_COLOR_COMMAND + "Mit viel Liebe gebacken von %s";
    String PLUGIN_COMMAND_COOKIES_LORE_3 = PLUGIN_COLOR_COMMAND + "Wie selbstverliebt!";
    String PLUGIN_COMMAND_COOKIES_DISPLAYNAME = PLUGIN_COLOR_COMMAND + "Schokoladenkeks";

    String PLUGIN_COMMAND_HEAD = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast ein Kopf von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erzeugt!";
    String PLUGIN_COMMAND_VANISH_DISABLE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast vanish für " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "deaktiviert!";
    String PLUGIN_COMMAND_VANISH_ENABLE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast vanish für " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "aktiviert!";
    String PLUGIN_COMMAND_VANISH = PLUGIN_FORMS_COMMAND_PREFIX + "Dein vanish wurde umgeschaltet!";

    String PLUGIN_COMMAND_MORE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast mehr von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erzeugt!";
    String PLUGIN_COMMAND_MORE_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast mehr von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erhalten!";

    String PLUGIN_COMMAND_REPAIR = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " repariert!";
    String PLUGIN_COMMAND_CANNOT_REPAIR = PLUGIN_FORMS_COMMAND_PREFIX + "Du kannst " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " nicht reparieren!";
    String PLUGIN_COMMAND_REPAIR_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " repariert bekommen!";

    String PLUGIN_COMMAND_GAMERULES = PLUGIN_FORMS_COMMAND_PREFIX + "Die Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "hat folgende Einstellungen:";

    String PLUGIN_COMMAND_HOME = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "an den Bett Spawn teleportiert!";
    String PLUGIN_COMMAND_HOME_TP = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest zu " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "teleportiert!";
    String PLUGIN_COMMAND_HOME_NONE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast kein Home!";

    String PLUGIN_COMMAND_HOME_LIST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast folgende Homes:";
    String PLUGIN_COMMAND_HOME_LIST_NAME =  PLUGIN_COLOR_COMMAND + "Name: " + PLUGIN_COLOR_COMMAND_ARG + "%s" + " §7(" + PLUGIN_COLOR_COMMAND_ARG + "%s§7)";
    String PLUGIN_COMMAND_HOME_LIST_DEATHPOINTS = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast folgende Todespunkte:";
    String PLUGIN_COMMAND_HOME_LIST_DEATHPOINTS_NAME =  PLUGIN_COLOR_COMMAND + "Todespunkt: " + PLUGIN_COLOR_COMMAND_ARG + "%s" + " §7(" + PLUGIN_COLOR_COMMAND_ARG + "%s§7)";

    String PLUGIN_COMMAND_HOME_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast kein Home mit dem Namen " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";
    String PLUGIN_COMMAND_HOME_EXISTS = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast bereits ein Home mit dem Namen " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";
    String PLUGIN_COMMAND_HOME_RESERVED = PLUGIN_FORMS_COMMAND_PREFIX + "Du kannst kein Home mit dem Namen " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " speichern!";
    String PLUGIN_COMMAND_HOME_NO_BED = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast kein Bett in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " an das du teleportiert werden kannst!";
    String PLUGIN_COMMAND_HOME_SET = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Home " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "gesetzt!";
    String PLUGIN_COMMAND_HOME_DELETE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Home " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "gelöscht!";
    String PLUGIN_COMMAND_HOME_DEATH_DELETE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Todespunkt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "gelöscht!";

    String PLUGIN_COMMAND_SUN = PLUGIN_FORMS_COMMAND_PREFIX + "Du lässt die Sonne in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "scheinen!";
    String PLUGIN_COMMAND_SUN_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Die Sonne die Sonne scheint nur für dich!";

    String PLUGIN_COMMAND_RAIN = PLUGIN_FORMS_COMMAND_PREFIX + "Du lässt es in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " regnen!";
    String PLUGIN_COMMAND_RAIN_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Es regnet nur für dich!";

    String PLUGIN_COMMAND_STORM = PLUGIN_FORMS_COMMAND_PREFIX + "Du lässt es in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " gewittern!";

    String PLUGIN_COMMAND_DAY = PLUGIN_FORMS_COMMAND_PREFIX + "Es ist jetzt Tag in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";

    String PLUGIN_COMMAND_GOD_ON = PLUGIN_FORMS_COMMAND_PREFIX + "Du bist der Gott!";
    String PLUGIN_COMMAND_GOD_OFF = PLUGIN_FORMS_COMMAND_PREFIX + "Du bist wieder sterblich!";

    String PLUGIN_COMMAND_HEAL = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest geheilt!"; 

    String PLUGIN_COMMAND_NIGHT = PLUGIN_FORMS_COMMAND_PREFIX + "Es ist jetzt Nacht in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";

    String PLUGIN_COMMAND_ENDERCHEST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast deine Enderchest geöffnet!";
    String PLUGIN_COMMAND_ENDERCHEST_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast die Enderchest von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "geöffnet!";

    String PLUGIN_COMMAND_INVENTORY = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Inventar geöffnet!";
    String PLUGIN_COMMAND_INVENTORY_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast das Inventar von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "geöffnet!";

    String PLUGIN_COMMAND_SPAWN = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "an den Spawn teleportiert!";

    String PLUGIN_COMMAND_NICK = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast den Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "umbenannt!";

    String PLUGIN_COMMAND_SUICIDE = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "hat sich umgebracht!";

    String PLUGIN_COMMAND_WHERE = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "befindet sich bei " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";
    String PLUGIN_COMMAND_WHERE_STRING = PLUGIN_COLOR_COMMAND + "X: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Y: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Z: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Welt: " + PLUGIN_COLOR_COMMAND_ARG + "%s";

    String PLUGIN_COMMAND_MSG_PLAYER_OFFLINE = PLUGIN_FORMS_COMMAND_PREFIX + "Spieler ist Offline!";
    String PLUGIN_COMMAND_MSG_NO_ONE_TO_REPLY = PLUGIN_FORMS_COMMAND_PREFIX + "Niemand da der dir antworten könnte!";
    String PLUGIN_COMMAND_MSG_SPACER_IN = "§9 >> §f";
    String PLUGIN_COMMAND_MSG_SPACER_OUT = "§9 << §f";
    String PLUGIN_COMMAND_MSG_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/msg " + PLUGIN_COLOR_COMMAND + "<" + PLUGIN_COLOR_COMMAND_ARG + "spieler" + PLUGIN_COLOR_COMMAND + ">" + " " + "<" + PLUGIN_COLOR_COMMAND_ARG + "nachricht" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_PRINT_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/print " + "<" + PLUGIN_COLOR_COMMAND_ARG + "nachricht" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_RENAME_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/rename " + "<" + PLUGIN_COLOR_COMMAND_ARG + "name" + PLUGIN_COLOR_COMMAND + ">";
    String PLUGIN_COMMAND_RENAME_AIR = PLUGIN_FORMS_COMMAND_PREFIX + "Du kannst Luft nicht umbenennen! ";
    String PLUGIN_COMMAND_RENAME = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Gegenstand umbenannt!";

    String PLUGIN_COMMAND_WORLD = PLUGIN_FORMS_COMMAND_PREFIX + "Folgende Welten gibt es:";
    String PLUGIN_COMMAND_WORLD_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Die Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " existiert nicht";

    String PLUGIN_COMMAND_POKE = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze /poke " + PLUGIN_COLOR_COMMAND_ARG + "<Name>" + PLUGIN_COLOR_COMMAND + " um einen Spieler anzustubsen";
    String PLUGIN_COMMAND_POKE_TITLE = "§4Buuuh";
    String PLUGIN_COMMAND_POKE_SUBTITLE = "~~~~~~~~~~~~~~";
    String PLUGIN_COMMAND_POKE_MESSAGE_TARGET = PLUGIN_FORMS_COMMAND_PREFIX + "%s " + PLUGIN_COLOR_COMMAND + "hat dich angestupst!";
    String PLUGIN_COMMAND_POKE_MESSAGE_SENDER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + "%s " + PLUGIN_COLOR_COMMAND + "angestupst!";

    String PLUGIN_COMMAND_SPEED = PLUGIN_FORMS_COMMAND_PREFIX + "Geschwindigkeit wurde auf " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " gesetzt";
    String PLUGIN_COMMAND_SPEED_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/speed " + "<" + PLUGIN_COLOR_COMMAND_ARG + "0-10" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_BROADCAST_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Um ein Title Broadcast zu machen nutze " + PLUGIN_COLOR_COMMAND_ARG + "/broadcast title " + PLUGIN_COLOR_COMMAND + "sonst " + PLUGIN_COLOR_COMMAND_ARG + "/broadcast " + PLUGIN_COLOR_COMMAND + "<" + PLUGIN_COLOR_COMMAND_ARG + "message" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_INVALID = PLUGIN_FORMS_COMMAND_PREFIX + "Invalid Data!";
    String PLUGIN_COMMAND_PERMISSION_MISSING = PLUGIN_FORMS_COMMAND_PREFIX + "Dafür hast du leider keine Rechte!";
    String PLUGIN_COMMAND_NOT_A_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du bist leider kein Spieler!";
    String PLUGIN_COMMAND_TO_LESS_ARGUMENTS = PLUGIN_FORMS_COMMAND_PREFIX + "Zu wenig Argumente!";
    String PLUGIN_COMMAND_TO_MANY_ARGUMENTS = PLUGIN_FORMS_COMMAND_PREFIX + "Zu viele Argumente!";
    String PLUGIN_COMMAND_TARGET_NOT_A_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "%s" + PLUGIN_COLOR_COMMAND + " ist kein Spieler!";
    String PLUGIN_COMMAND_WRONG_SUB_COMMAND = PLUGIN_FORMS_COMMAND_PREFIX + "Wrong Sub Command";   

    String PLUGIN_COMMAND_PURSE_GAIN = PLUGIN_FORMS_COMMAND_PREFIX + "You gained " + PLUGIN_COLOR_MONEY + "%s " + PLUGIN_NAME_MONEY + " and now have " + PLUGIN_COLOR_MONEY + "%s " + PLUGIN_NAME_MONEY + " in your Purse!";
    String PLUGIN_COMMAND_PURSE_TO_ITEM = PLUGIN_FORMS_COMMAND_PREFIX + "You put out " + PLUGIN_COLOR_MONEY + "%s " + PLUGIN_NAME_MONEY;
    String PLUGIN_COMMAND_PURSE_TO_ITEM_VALUE_INVALID = PLUGIN_FORMS_COMMAND_PREFIX + "The value you entered is invalid!";
    String PLUGIN_COMMAND_PURSE_TO_ITEM_NOT_ENOUGH_MONEY = PLUGIN_FORMS_COMMAND_PREFIX + "Not enough " + PLUGIN_NAME_MONEY;
    String PLUGIN_COMMAND_PURSE_TOTAL = PLUGIN_FORMS_COMMAND_PREFIX + "You have " + PLUGIN_COLOR_MONEY + "%s " + PLUGIN_NAME_MONEY + " in your Purse!";
    String PLUGIN_COMMAND_PURSE_TOTAL_OTHER = PLUGIN_FORMS_COMMAND_PREFIX + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " has " + PLUGIN_COLOR_MONEY + "%s " + PLUGIN_NAME_MONEY + " in the Purse!";

    String PLUGIN_COMMAND_PROTECT_COMMAND_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use " + PLUGIN_COLOR_COMMAND_NAME + "/%s " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_MESSAGE + ", " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_MESSAGE + ", " + PLUGIN_COLOR_COMMAND_ARG + "%s"+ PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_PROTECT_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Click a Protected Block to view the Protection Info";
    String PLUGIN_COMMAND_PROTECT_ADD = PLUGIN_FORMS_COMMAND_PREFIX + "Click Protectable Block to create a Protection";
    String PLUGIN_COMMAND_PROTECT_REMOVE = PLUGIN_FORMS_COMMAND_PREFIX + "Click your Protected Block to remove the Protection";
    String PLUGIN_COMMAND_PROTECT_FLAG = PLUGIN_FORMS_COMMAND_PREFIX + "Use " + PLUGIN_COLOR_COMMAND_NAME + "/%s " + PLUGIN_COLOR_COMMAND_ARG + "%s %s" + PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s flagname";
    String PLUGIN_COMMAND_PROTECT_FLAG_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Flag was not found!";
    String PLUGIN_COMMAND_PROTECT_RIGHT = PLUGIN_FORMS_COMMAND_PREFIX + "Use " + PLUGIN_COLOR_COMMAND_NAME + "/%s " + PLUGIN_COLOR_COMMAND_ARG + "%s %s"  + PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s playername";
    String PLUGIN_COMMAND_PROTECT_FLAG_ADD = PLUGIN_FORMS_COMMAND_PREFIX + "Click your Protected Block to add the Flag";
    String PLUGIN_COMMAND_PROTECT_FLAG_REMOVE = PLUGIN_FORMS_COMMAND_PREFIX + "Click your Protected Block to remove the Flag";
    String PLUGIN_COMMAND_PROTECT_RIGHT_ADD = PLUGIN_FORMS_COMMAND_PREFIX + "Click your Protected Block to add the Player";
    String PLUGIN_COMMAND_PROTECT_RIGHT_PLAYER_NOTFOUND = PLUGIN_FORMS_COMMAND_PREFIX + "No Player found with Name: " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_PROTECT_RIGHT_REMOVE = PLUGIN_FORMS_COMMAND_PREFIX + "Click your Protected Block to remove the Player";

    String PLUGIN_COMMAND_SIGN_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use " + PLUGIN_COLOR_COMMAND_NAME + "/%s" + " " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_SIGN_COPY = PLUGIN_FORMS_COMMAND_PREFIX + "Click the Sign you want to copy";
    String PLUGIN_COMMAND_SIGN_EDIT = PLUGIN_FORMS_COMMAND_PREFIX + "Click the Sign you want to edit";
    String PLUGIN_COMMAND_ADMIN_LIGHT_TOOGLE = PLUGIN_FORMS_COMMAND_PREFIX + "Click the Redstone Lamp you want to Lit. Use this Command again to disable the Light Toogle Mode.";
    String PLUGIN_COMMAND_ADMIN_LIGHT_TOOGLE_DISABLED = PLUGIN_FORMS_COMMAND_PREFIX + "Light Toogle Mode is now disabled.";
    String PLUGIN_COMMAND_ADMIN_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use this command with the following Subcommands: npc, chat, light, afk, top, ping, cleanProtections";
    String PLUGIN_COMMAND_ADMIN_CHAT_CLEARED = PLUGIN_FORMS_COMMAND_PREFIX + "Chat was cleared";
    String PLUGIN_COMMAND_ADMIN_TOP = PLUGIN_FORMS_COMMAND_PREFIX + "Teleported to the highest Block";
    String PLUGIN_COMMAND_ADMIN_CLEAN_PROTECTIONS ="ID: " + PLUGIN_COLOR_COMMAND_ARG + "#%s" + PLUGIN_COLOR_COMMAND + " PMat: " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " != LMat: " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_ADMIN_CLEAN_PROTECTIONS_START = PLUGIN_FORMS_COMMAND_PREFIX + "Checking " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " Protection Materials against their Location Materials";
    String PLUGIN_COMMAND_ADMIN_CLEAN_PROTECTIONS_CLEANING_UP = PLUGIN_FORMS_COMMAND_PREFIX + "Cleaning Up " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " Protections";
    String PLUGIN_COMMAND_ADMIN_CLEAN_PROTECTIONS_END = PLUGIN_FORMS_COMMAND_PREFIX + "Reduced to " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " Protections";
    String PLUGIN_COMMAND_ADMIN_CLEAN_PROTECTIONS_NONE = PLUGIN_FORMS_COMMAND_PREFIX + "No Protections to Clean Up";
    String PLUGIN_COMMAND_WORLD_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use this command with the following Subcommands: list load unload unloadNoSave";
    String PLUGIN_COMMAND_WORLD_CREATE_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use this command with the following arguments: name(String) type(WordType String) environment (Environment as String) structures (boolean)";
    String PLUGIN_COMMAND_WORLD_WORLD_NOT_LOADED = "World not loaded. Can't unload this World.";
    String PLUGIN_COMMAND_WORLD_UNLOAD_WORLD = PLUGIN_FORMS_COMMAND_PREFIX + "World get's saved and unloaded.";
    String PLUGIN_COMMAND_WORLD_UNLOAD_WORLD_NO_SAVE = PLUGIN_FORMS_COMMAND_PREFIX + "World get's unloaded without saving it.";
    String PLUGIN_COMMAND_WORLD_LOAD_WORLD = PLUGIN_FORMS_COMMAND_PREFIX + "World get's loaded.";
    String PLUGIN_COMMAND_WORLD_CREATE_WORLD = PLUGIN_FORMS_COMMAND_PREFIX + "World get's created.";
    String PLUGIN_COMMAND_WORLD_WRONG_ARGUMENTS = PLUGIN_FORMS_COMMAND_PREFIX + "Can't create World, wrong parameters given!";
    String PLUGIN_COMMAND_SUDO_ACTIVATED = PLUGIN_FORMS_COMMAND_PREFIX + "You are now sudoing %s";
    String PLUGIN_COMMAND_SUDO_DEACTIVATED = PLUGIN_FORMS_COMMAND_PREFIX + "Exited.";
    String PLUGIN_COMMAND_SUDO_PLAYER_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Can't Sudo Player " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + ". Player not found!";
    String PLUGIN_COMMAND_EXIT_KICK_MESSAGE = PLUGIN_COLOR_COMMAND + "exited.";
    String PLUGIN_COMMAND_EXIT_SERVER_SHUTTING_DOWN = PLUGIN_COLOR_COMMAND + "Server is shutting down...";


    String PLUGIN_COMMAND_TP_REQUEST_TARGET = PLUGIN_FORMS_COMMAND_PREFIX + "Teleport Anfrage von " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND;
    String PLUGIN_COMMAND_TP_REQUEST_EXPIRED = PLUGIN_FORMS_COMMAND_PREFIX + "Teleport Anfrage ist abgelaufen!";
    String PLUGIN_COMMAND_TP = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest zu " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "teleportiert!";
    String PLUGIN_COMMAND_TP_TO = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "zu  dir teleportiert!";
    String PLUGIN_COMMAND_TP_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/teleport <name> " + PLUGIN_COLOR_COMMAND + "," + PLUGIN_COLOR_COMMAND_ARG + "/teleport accept"+ PLUGIN_COLOR_COMMAND + ", " + PLUGIN_COLOR_COMMAND_ARG + "/teleport to <name>" + PLUGIN_COLOR_COMMAND + " oder " + PLUGIN_COLOR_COMMAND_ARG + "/teleport <x> <y> <z>";
    String PLUGIN_COMMAND_TP_ACCEPT_NO_REQUEST = PLUGIN_FORMS_COMMAND_PREFIX + "Keine offene Teleport Anfrage!";
    String PLUGIN_COMMAND_TP_SEND_REQUEST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast eine Teleport Anfrage an " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " geschickt!";

    String PLUGIN_GRAPPLING_HOOK_COOLDOWN = PLUGIN_COLOR_NEGATIVE + "Please Slow down..";

    String PLUGIN_BAG_AMOUNT = "Amount: " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_BAG_RETRIEVE = "Click to retrieve";
    String PLUGIN_BAG_CLICK_TO_OPEN = "Click to open";
    String PLUGIN_BAG_CLICK_TO_BUY = "Click to buy this Bag";
    String PLUGIN_BAG_COST_TO_BUY = "Costs: %s";
    String PLUGIN_BAG_GUI_TITLE =  PLUGIN_NAME_PREFIX + PLUGIN_FORMS_SPACER_MESSAGE + "Bags";

    String PLUGIN_BAGS_SAVED = "%s%s Bag(s) saved!";
    String PLUGIN_PLAYERS_SAVED = "%s%s Player(s) saved!";
    String PLUGIN_PLAYERS_INVENTORY_SAVED = "%s%s Player(s) Inventory saved!";
    String PLUGIN_COMMAND_BAGS_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "The searched Bag " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "was not found!";

    String PLUGIN_COMMAND_MARRY_SEND_REQUEST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast eine Hochzeitsanfrage an " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " geschickt!";
    String PLUGIN_COMMAND_MARRY_RECEIVE_REQUEST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast eine Hochzeitsanfrage von " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " bekommen!";
    String PLUGIN_COMMAND_MARRY_MARRIED = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "geheiratet!";
    String PLUGIN_COMMAND_MARRY_REQUEST_EXPIRED = PLUGIN_FORMS_COMMAND_PREFIX + "Hochzeitsanfrage ist abgelaufen!";
    String PLUGIN_COMMAND_MARRY_REQUEST_IS_MARRIED = PLUGIN_FORMS_COMMAND_PREFIX + "Hochzeitsanfrage ist ungültig, Spieler ist bereits verheitratet!";
    String PLUGIN_COMMAND_MARRY_ACCEPT_NO_REQUEST = PLUGIN_FORMS_COMMAND_PREFIX + "Keine offene Hochzeitsanfrage!";
    String PLUGIN_COMMAND_MARRY_DIVORCE_NOT_MARRIED = PLUGIN_FORMS_COMMAND_PREFIX + "Du bist nicht verheiratet!";
    String PLUGIN_COMMAND_MARRY_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/marry <name>" + PLUGIN_COLOR_COMMAND + ", " + PLUGIN_COLOR_COMMAND_ARG + "/marry accept"+ PLUGIN_COLOR_COMMAND + " oder " + PLUGIN_COLOR_COMMAND_ARG + "/marry divorce";
    String PLUGIN_COMMAND_MARRY_DIVORCED = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dich von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "getrennt!";
    String PLUGIN_COMMAND_MARRY_SELF_MARRIAGE = PLUGIN_FORMS_COMMAND_PREFIX + "Du kannst dich nicht selbst heiraten!";

    String PLUGIN_COMMAND_BACK = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest zurück teleportiert!";
    String PLUGIN_COMMAND_BACK_NO_LOCATION = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast kein Back Punkt gesetzt!";


    String PLUGIN_COMMAND_WARP = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest gewarped!";
    String PLUGIN_COMMAND_WARP_LIST_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Warp Liste:";
    String PLUGIN_COMMAND_WARP_LIST = PLUGIN_COLOR_COMMAND + "Warp Name: " + PLUGIN_COLOR_COMMAND_ARG + "%s ";
    String PLUGIN_COMMAND_WARP_ERROR_WORLD_UNLOADED = PLUGIN_FORMS_COMMAND_PREFIX + "Error, Welt ist nicht geladen!";
    String PLUGIN_COMMAND_WARP_ERROR_NO_WARP_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Kein Warp mit diesem Namen gefunden!";
    String PLUGIN_COMMAND_WARP_ADD = PLUGIN_FORMS_COMMAND_PREFIX + "Warp mit dem Namen %s wurde hinzugefügt!";
    String PLUGIN_COMMAND_WARP_REMOVE = PLUGIN_FORMS_COMMAND_PREFIX + "Warp mit dem Namen %s wurde entfernt!";


    String PLUGIN_COMMAND_SETGROUP = PLUGIN_COLOR_COMMAND + "Group " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " for Player " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " was set!";
    String PLUGIN_COMMAND_SETGROUP_GROUP_NOT_FOUND = PLUGIN_COLOR_COMMAND + "Group " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " not found!";
    String PLUGIN_BANK_INTEREST_NEXT_RUN = PLUGIN_COLOR_COMMAND + "Next Interest Payment Run in: " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " seconds!";

    String PLUGIN_COMMAND_CUSTOMHEADS_TITLE = PLUGIN_FORMS_COMMAND_PREFIX + "Heads";

    String PLUGIN_COMMAND_PLAYERINFO = PLUGIN_FORMS_COMMAND_PREFIX + "Player Information: " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_PLAYERINFO_HOMES = "Homes: %s";
    String PLUGIN_COMMAND_PLAYERINFO_DEATHPOINTS = "DeathPoints: %s";
    String PLUGIN_COMMAND_PLAYERINFO_GROUP = "Group: %s";
    String PLUGIN_COMMAND_PLAYERINFO_MARRIED_TO = "Married: %s " + PLUGIN_SYMBOL_HEART + PLUGIN_COLOR_COMMAND + " %s";
    String PLUGIN_COMMAND_PLAYERINFO_MARRIED_SINCE = "Married since: %s";
    String PLUGIN_COMMAND_PLAYERINFO_LAST_ONLINE = "Last Online: %s";
    String PLUGIN_COMMAND_PLAYERINFO_FIRST_ONLINE = "First Online: %s";
    String PLUGIN_COMMAND_PLAYERINFO_MINED = "%s mined: %s";
    String PLUGIN_COMMAND_PLAYERINFO_DEATHS = "Deaths: %s";
    String PLUGIN_COMMAND_PLAYERINFO_JUMPED = "Jumped: %s";
    String PLUGIN_COMMAND_PLAYERINFO_LEFT_GAME = "Left Game: %s";

    String PLUGIN_COMMAND_TEAM_TITLE = PLUGIN_FORMS_COMMAND_PREFIX + "Team:";

    String PLUGIN_ITEM_SELL_PRICE_MESSAGE = PLUGIN_COLOR_NEGATIVE + "Sell: " + PLUGIN_NAME_MONEY + " per Item: %s " + PLUGIN_NAME_MONEY + " per Stack: %s";
    String PLUGIN_ITEM_BUY_PRICE_MESSAGE = PLUGIN_COLOR_POSITIVE + "Buy: " + PLUGIN_NAME_MONEY + " per Item: %s " + PLUGIN_NAME_MONEY + " per Stack: %s";
}
