package de.relluem94.minecraft.server.spigot.essentials.constants;

public interface Constants {
    
    /* ******************************************************************************* */
    /*                               PLUGIN   STUFF                                    */
    /* ******************************************************************************* */

    String PLUGIN_EOL = System.lineSeparator();

    String PLUGIN_COLOR_COMMAND = "§f";
    String PLUGIN_COLOR_COMMAND_NAME = "§b";
    String PLUGIN_COLOR_COMMAND_ARG = "§b";
    String PLUGIN_COLOR_MESSAGE = "§f";
    String PLUGIN_COLOR_CONSOLE = "§c";
    String PLUGIN_COLOR_COMMAND_BLOCK = "§8";
    String PLUGIN_COLOR_MONEY = "§6"; 
    String PLUGIN_COLOR_BROADCAST = "§5";
    String PLUGIN_COLOR_MESSAGE_SPACER = "§7";
    String PLUGIN_COLOR_RESET = "§r";
    String PLUGIN_COLOR_LOGO_RELLU = "§8";
    String PLUGIN_COLOR_LOGO_ESSENTIALS = "§c";
    String PLUGIN_COLOR_POSITIVE = "§a";
    String PLUGIN_COLOR_NEGATIVE = "§c";
    String PLUGIN_COLOR_NEUTRAL = "§6";
    

    String PLUGIN_NAME_RELLU = "Rellu";
    String PLUGIN_NAME_ESSENTIALS = "Essentials";
    String PLUGIN_NAME_INITIAL_RELLU = "R";
    String PLUGIN_NAME_INITIAL_ESSENTIALS = "E";
    String PLUGIN_NAME_SHORT = PLUGIN_COLOR_LOGO_RELLU + PLUGIN_NAME_INITIAL_RELLU + PLUGIN_COLOR_LOGO_ESSENTIALS + PLUGIN_NAME_INITIAL_ESSENTIALS + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_NAME_PREFIX = PLUGIN_COLOR_LOGO_RELLU + PLUGIN_NAME_RELLU + PLUGIN_COLOR_LOGO_ESSENTIALS + PLUGIN_NAME_ESSENTIALS + PLUGIN_COLOR_RESET + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_NAME_CONSOLE = PLUGIN_COLOR_MESSAGE + "[" + PLUGIN_NAME_PREFIX + PLUGIN_COLOR_MESSAGE + "] ";
    String PLUGIN_NAME_BROADCAST = PLUGIN_COLOR_BROADCAST + "Broadcast";
    String PLUGIN_NAME_CHAT_CONSOLE = PLUGIN_COLOR_CONSOLE + "Console";
    String PLUGIN_NAME_MONEY = PLUGIN_COLOR_MONEY + "Coins" + PLUGIN_COLOR_MESSAGE; 

    String PLUGIN_WORLD_LOBBY = "lobby";
    String PLUGIN_WORLD_WORLD = "world";
    String PLUGIN_WORLD_WORLD_NETHER = "world_nether";
    String PLUGIN_WORLD_WORLD_THE_END = "world_the_end";

    String PLUGIN_FORMS_SPACER_CHANNEL = " >> " + PLUGIN_COLOR_COMMAND;
    String PLUGIN_FORMS_SPACER_MESSAGE = PLUGIN_COLOR_MESSAGE_SPACER + " >> " + PLUGIN_COLOR_MESSAGE;
    String PLUGIN_FORMS_BORDER = "<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>";
    String PLUGIN_FORMS_WHITESPACE_SHORT = "    ";
    String PLUGIN_FORMS_COMMAND_PREFIX = PLUGIN_NAME_PREFIX + PLUGIN_FORMS_SPACER_MESSAGE + PLUGIN_COLOR_COMMAND;

    String PLUGIN_SYMBOL_HEAVY_CHECK_MARK = PLUGIN_COLOR_POSITIVE + "✔ ";
    String PLUGIN_SYMBOL_BLACK_LARGE_CIRCLE = PLUGIN_COLOR_NEUTRAL + "⬤ ";
    String PLUGIN_SYMBOL_HEAVY_MULTIPLICATION_X = PLUGIN_COLOR_NEGATIVE + "✖ ";
    String PLUGIN_SYMBOL_RIGHT_POINTING_ANGLE_BRACKET = PLUGIN_COLOR_POSITIVE + "〉";
    String PLUGIN_SYMBOL_LEFT_POINTING_ANGLE_BRACKET = PLUGIN_COLOR_NEGATIVE + "〈";
    String PLUGIN_SYMBOL_CROSS_MARK = PLUGIN_COLOR_NEGATIVE + "❌";
    String PLUGIN_SYMBOL_BLACK_FOUR_POINTED_STAR = PLUGIN_COLOR_POSITIVE + "✦";

    String PLUGIN_SIGN_NAME = PLUGIN_COLOR_MESSAGE + "[" + PLUGIN_NAME_SHORT + "]";
    String PLUGIN_SIGN_CLICK = PLUGIN_COLOR_MESSAGE + "[Click here]";

    String PLUGIN_INTERNAL_UTILITY_CLASS = "This is a Utility Class";

    /* ******************************************************************************* */
    /*                              COMMAND   STUFF                                    */
    /* ******************************************************************************* */

    String PLUGIN_COMMAND_CRAFTINGBENCH = PLUGIN_FORMS_COMMAND_PREFIX + "Die Werkbank von %s" + PLUGIN_COLOR_COMMAND + " wurde geöffnet!";
    String PLUGIN_COMMAND_HEAD = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast ein Kopf von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erzeugt!";

    String PLUGIN_COMMAND_MORE = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast mehr von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erzeugt!";
    String PLUGIN_COMMAND_MORE_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast mehr von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + " erhalten!";

    String PLUGIN_COMMAND_ENDERCHEST = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast deine Enderchest geöffnet!";
    String PLUGIN_COMMAND_ENDERCHEST_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast die Enderchest von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "geöffnet!";

    String PLUGIN_COMMAND_INVENTORY = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Inventar geöffnet!";
    String PLUGIN_COMMAND_INVENTORY_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast das Inventar von " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "geöffnet!";

    String PLUGIN_COMMAND_SPAWN = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest in der Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "an den Spawn teleportiert!";

    String PLUGIN_COMMAND_NICK = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast den Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "umbenannt!";

    String PLUGIN_COMMAND_SUICIDE = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "hat sich umgebracht!";

    String PLUGIN_COMMAND_WHERE = PLUGIN_FORMS_COMMAND_PREFIX + "Der Spieler " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "befindet sich bei " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + "!";
    String PLUGIN_COMMAND_WHERE_STRING = PLUGIN_COLOR_COMMAND + "X: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Y: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Z: " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "Welt: " + PLUGIN_COLOR_COMMAND_ARG + "%s";

    String PLUGIN_COMMAND_MSG_PLAYER_OFFLINE = PLUGIN_FORMS_COMMAND_PREFIX + "Spieler ist Offline!";
    String PLUGIN_COMMAND_MSG_NO_ONE_TO_REPLY = PLUGIN_FORMS_COMMAND_PREFIX + "Niemand da der dir antworten könnte!";
    String PLUGIN_COMMAND_MSG_SPACER_IN = "§9 >> §f";
    String PLUGIN_COMMAND_MSG_SPACER_OUT = "§9 << §f";
    String PLUGIN_COMMAND_MSG_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/msg " + PLUGIN_COLOR_COMMAND + "<" + PLUGIN_COLOR_COMMAND_ARG + "spieler" + PLUGIN_COLOR_COMMAND + ">" + " " + "<" + PLUGIN_COLOR_COMMAND_ARG + "nachricht" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_PRINT_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/print " + "<" + PLUGIN_COLOR_COMMAND_ARG + "nachricht" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_RENAME_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/rename " + "<" + PLUGIN_COLOR_COMMAND_ARG + "name" + PLUGIN_COLOR_COMMAND + ">";
    String PLUGIN_COMMAND_RENAME_AIR = PLUGIN_FORMS_COMMAND_PREFIX + "Du kannst Luft nicht umbenennen! ";
    String PLUGIN_COMMAND_RENAME = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast dein Gegenstand umbenannt!";

    String PLUGIN_COMMAND_WORLD_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "Die Welt " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " existiert nicht";

    String PLUGIN_COMMAND_POKE = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze /poke " + PLUGIN_COLOR_COMMAND_ARG + "<Name>" + PLUGIN_COLOR_COMMAND + " um einen Spieler anzustubsen";
    String PLUGIN_COMMAND_POKE_TITLE = "§4Buuuh";
    String PLUGIN_COMMAND_POKE_SUBTITLE = "~~~~~~~~~~~~~~";
    String PLUGIN_COMMAND_POKE_MESSAGE_TARGET = PLUGIN_FORMS_COMMAND_PREFIX + "%s " + PLUGIN_COLOR_COMMAND + "hat dich angestupst!";
    String PLUGIN_COMMAND_POKE_MESSAGE_SENDER = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast " + "%s " + PLUGIN_COLOR_COMMAND + "angestupst!";

    String PLUGIN_COMMAND_SPEED = PLUGIN_FORMS_COMMAND_PREFIX + "Geschwindigkeit wurde auf " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " gesetzt";
    String PLUGIN_COMMAND_SPEED_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Nutze " + PLUGIN_COLOR_COMMAND_ARG + "/speed " + "<" + PLUGIN_COLOR_COMMAND_ARG + "0-10" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_BROADCAST_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Um ein Title Broadcast zu machen nutze " + PLUGIN_COLOR_COMMAND_ARG + "/broadcast title " + PLUGIN_COLOR_COMMAND + "sonst " + PLUGIN_COLOR_COMMAND_ARG + "/broadcast " + PLUGIN_COLOR_COMMAND + "<" + PLUGIN_COLOR_COMMAND_ARG + "message" + PLUGIN_COLOR_COMMAND + ">";

    String PLUGIN_COMMAND_INVALID = PLUGIN_FORMS_COMMAND_PREFIX + "Invalid Data!";
    String PLUGIN_COMMAND_PERMISSION_MISSING = PLUGIN_FORMS_COMMAND_PREFIX + "Dafür hast du leider keine Rechte!";
    String PLUGIN_COMMAND_NOT_A_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "Du bist leider kein Spieler!";
    String PLUGIN_COMMAND_TO_LESS_ARGUMENTS = PLUGIN_FORMS_COMMAND_PREFIX + "Zu wenig Argumente!";
    String PLUGIN_COMMAND_TO_MANY_ARGUMENTS = PLUGIN_FORMS_COMMAND_PREFIX + "Zu viele Argumente!";
    String PLUGIN_COMMAND_TARGET_NOT_A_PLAYER = PLUGIN_FORMS_COMMAND_PREFIX + "%s" + PLUGIN_COLOR_COMMAND + " ist kein Spieler!";
    String PLUGIN_COMMAND_WRONG_SUB_COMMAND = PLUGIN_FORMS_COMMAND_PREFIX + "Wrong Sub Command";   

    String PLUGIN_COMMAND_SIGN_INFO = PLUGIN_FORMS_COMMAND_PREFIX + "Use " + PLUGIN_COLOR_COMMAND_NAME + "/%s" + " " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_MESSAGE + " or " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_COMMAND_SIGN_COPY = PLUGIN_FORMS_COMMAND_PREFIX + "Click the Sign you want to copy";
    String PLUGIN_COMMAND_SIGN_EDIT = PLUGIN_FORMS_COMMAND_PREFIX + "Click the Sign you want to edit";

    String PLUGIN_COMMAND_EXIT_KICK_MESSAGE = PLUGIN_COLOR_COMMAND + "exited.";
    String PLUGIN_COMMAND_EXIT_SERVER_SHUTTING_DOWN = PLUGIN_COLOR_COMMAND + "Server is shutting down...";

    String PLUGIN_BAG_AMOUNT = "Amount: " + PLUGIN_COLOR_COMMAND_ARG + "%s";
    String PLUGIN_BAG_RETRIEVE = "Click to retrieve";
    String PLUGIN_BAG_CLICK_TO_OPEN = "Click to open";
    String PLUGIN_BAG_CLICK_TO_BUY = "Click to buy this Bag";
    String PLUGIN_BAG_COST_TO_BUY = "Costs: %s";
    String PLUGIN_BAG_GUI_TITLE =  PLUGIN_NAME_PREFIX + PLUGIN_FORMS_SPACER_MESSAGE + "Bags";

    String PLUGIN_BAGS_SAVED = "%s%s Bag(s) saved!";
    String PLUGIN_PLAYERS_SAVED = "%s%s Player(s) saved!";
    String PLUGIN_PLAYERS_INVENTORY_SAVED = "%s%s Player(s) Inventory saved!";
    String PLUGIN_COMMAND_BAGS_NOT_FOUND = PLUGIN_FORMS_COMMAND_PREFIX + "The searched Bag " + PLUGIN_COLOR_COMMAND_ARG + "%s " + PLUGIN_COLOR_COMMAND + "was not found!";

    String PLUGIN_COMMAND_BACK = PLUGIN_FORMS_COMMAND_PREFIX + "Du wurdest zurück teleportiert!";
    String PLUGIN_COMMAND_BACK_NO_LOCATION = PLUGIN_FORMS_COMMAND_PREFIX + "Du hast kein Back Punkt gesetzt!";

    String PLUGIN_COMMAND_SETGROUP = PLUGIN_COLOR_COMMAND + "Group " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " for Player " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " was set!";
    String PLUGIN_COMMAND_SETGROUP_GROUP_NOT_FOUND = PLUGIN_COLOR_COMMAND + "Group " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " not found!";
    String PLUGIN_BANK_INTEREST_NEXT_RUN = PLUGIN_COLOR_COMMAND + "Next Interest Payment Run in: " + PLUGIN_COLOR_COMMAND_ARG + "%s" + PLUGIN_COLOR_COMMAND + " seconds!";

    String PLUGIN_COMMAND_CUSTOMHEADS_TITLE = PLUGIN_FORMS_COMMAND_PREFIX + "Heads";

    String PLUGIN_COMMAND_LIST_HEADER = PLUGIN_FORMS_COMMAND_PREFIX + "Online Players " + PLUGIN_COLOR_MESSAGE_SPACER + "[" + PLUGIN_COLOR_NEUTRAL + "%s" + PLUGIN_COLOR_MESSAGE_SPACER + "]" + PLUGIN_COLOR_MESSAGE + ":";
    String PLUGIN_COMMAND_LIST_ENTRY = PLUGIN_FORMS_WHITESPACE_SHORT + PLUGIN_COLOR_MESSAGE_SPACER + "- " + "%s%s " + PLUGIN_COLOR_MESSAGE_SPACER + "[" + "%s%s" + PLUGIN_COLOR_MESSAGE_SPACER + "]";

    String PLUGIN_ITEM_SELL_PRICE_MESSAGE = PLUGIN_COLOR_NEGATIVE + "Sell: " + PLUGIN_NAME_MONEY + " per Item: %s " + PLUGIN_NAME_MONEY + " per Stack: %s";
    String PLUGIN_ITEM_BUY_PRICE_MESSAGE = PLUGIN_COLOR_POSITIVE + "Buy: " + PLUGIN_NAME_MONEY + " per Item: %s " + PLUGIN_NAME_MONEY + " per Stack: %s";

    String PLUGIN_POSITION_HIGHLIGHTING_DIFFERENT_WORLDS = PLUGIN_FORMS_COMMAND_PREFIX + "Positions are in different worlds, cannot highlight.";
}