package de.relluem94.minecraft.server.spigot.essentials.constants;

import lombok.Getter;

@Getter
public enum MessageKey {
    PLUGIN_MANAGER_START_MESSAGE("plugin.manager.start_message"),
    PLUGIN_MANAGER_STOP_MESSAGE("plugin.manager.stop_message"),
    PLUGIN_MANAGER_START_TIME_MESSAGE("plugin.manager.start_time_message"),
    PLUGIN_MANAGER_REGISTER_SKILLS("plugin.manager.register_skills"),
    PLUGIN_MANAGER_SKILLS_REGISTERED("plugin.manager.skills_registered"),
    PLUGIN_MANAGER_LOADING_CONFIGS("plugin.manager.loading_configs"),
    PLUGIN_MANAGER_CONFIGS_LOADED("plugin.manager.configs_loaded"),
    PLUGIN_MANAGER_REGISTER_EVENTS("plugin.manager.register_events"),
    PLUGIN_MANAGER_EVENTS_REGISTERED("plugin.manager.events_registered"),
    PLUGIN_MANAGER_REGISTER_RECIPE("plugin.manager.register_recipe"),
    PLUGIN_MANAGER_RECIPE_REGISTERED("plugin.manager.recipe_registered"),
    PLUGIN_MANAGER_REGISTER_COMMANDS("plugin.manager.register_commands"),
    PLUGIN_MANAGER_COMMANDS_REGISTERED("plugin.manager.commands_registered"),
    PLUGIN_MANAGER_REGISTER_AUTOSAVE("plugin.manager.register_autosave"),
    PLUGIN_MANAGER_AUTOSAVE_REGISTERED("plugin.manager.autosave_registered"),
    PLUGIN_FOLDER_MKDIR_ERROR("plugin.folder.mkdir_error"),

    COMMAND_INVALID("command.invalid"),
    COMMAND_PERMISSION_MISSING("command.permission_missing"),
    COMMAND_NOT_A_PLAYER("command.not_a_player"),
    COMMAND_TARGET_NOT_A_PLAYER("command.target_not_a_player"),
    COMMAND_NO_PLAYER_IN_REACH("command.no_player_in_reach"),
    COMMAND_TO_LESS_ARGUMENTS("command.to_less_arguments"),
    COMMAND_TO_MANY_ARGUMENTS("command.to_many_arguments"),
    COMMAND_WRONG_SUB_COMMAND("command.wrong_sub_command"),

    COMMAND_FLYMODE("command.flymode"),
    COMMAND_FLYMODE_ACTIVATED("command.flymode.activated"),
    COMMAND_FLYMODE_DEACTIVATED("command.flymode.deactivated"),

    COMMAND_GAMEMODE("command.gamemode"),
    COMMAND_GAMEMODE_SURVIVAL("command.gamemode.survival"),
    COMMAND_GAMEMODE_CREATIVE("command.gamemode.creative"),
    COMMAND_GAMEMODE_ADVENTURE("command.gamemode.adventure"),
    COMMAND_GAMEMODE_SPECTATOR("command.gamemode.spectator"),

    COMMAND_AFK_ACTIVATED("command.afk.activated"),
    COMMAND_AFK_DEACTIVATED("command.afk.deactivated"),

    COMMAND_HOME("command.home"),
    COMMAND_HOME_TP("command.home.tp"),
    COMMAND_HOME_NONE("command.home.none"),
    COMMAND_HOME_SET("command.home.set"),
    COMMAND_HOME_DELETE("command.home.delete"),
    COMMAND_HOME_NOT_FOUND("command.home.not_found"),
    COMMAND_HOME_EXISTS("command.home.exists"),
    COMMAND_HOME_RESERVED("command.home.reserved"),
    COMMAND_HOME_LIST("command.home.list"),
    COMMAND_HOME_LIST_NAME("command.home.list_name"),
    COMMAND_HOME_LIST_DEATHPOINTS("command.home.list_deathpoints"),
    COMMAND_HOME_LIST_DEATHPOINTS_NAME("command.home.list_deathpoints_name"),
    COMMAND_HOME_DEATH_DELETE("command.home.death_delete"),
    COMMAND_HOME_NO_BED("command.home.no_bed"),

    COMMAND_MODIFY_NO_UNDO_HISTORY("command.modify.no_undo_history"),
    COMMAND_MODIFY_UNDO_STARTED("command.modify.undo_started"),
    COMMAND_MODIFY_WRONG_MATERIAL("command.modify.wrong_material"),
    COMMAND_MODIFY_NO_POSITIONS("command.modify.no_positions"),
    COMMAND_MODIFY_POS_1_EMPTY("command.modify.pos_1_empty"),
    COMMAND_MODIFY_POS_2_EMPTY("command.modify.pos_2_empty"),
    COMMAND_MODIFY_DIFFERENT_WORLDS("command.modify.different_worlds"),
    COMMAND_MODIFY_SET_STARTED("command.modify.set_started"),
    COMMAND_MODIFY_MOVE_STARTED("command.modify.move_started"),
    COMMAND_MODIFY_REPLACE_STARTED("command.modify.replace_started"),
    COMMAND_MODIFY_COPY_STARTED("command.modify.copy_started"),
    COMMAND_MODIFY_CUT_STARTED("command.modify.cut_started"),
    COMMAND_MODIFY_PASTE_STARTED("command.modify.paste_started"),
    COMMAND_MODIFY_NO_CLIPBOARD("command.modify.no_clipboard"),
    COMMAND_MODIFY_WALL_STARTED("command.modify.wall_started"),
    COMMAND_MODIFY_CYLINDER_STARTED("command.modify.cylinder_started"),
    COMMAND_MODIFY_FILL_STARTED("command.modify.fill_started"),
    COMMAND_MODIFY_FILLR_STARTED("command.modify.fillr_started"),
    COMMAND_MODIFY_FILL_RADIUS_TO_HIGH("command.modify.fill_radius_to_high"),
    COMMAND_MODIFY_CLIPBOARD_ROTATE_SUCCESS("command.modify.clipboard_rotate_success"),
    COMMAND_MODIFY_PLANT_STARTED("command.modify.plant_started"),

    COMMAND_ADMIN_LIGHT_TOGGLE("command.admin.light_toggle"),
    COMMAND_ADMIN_LIGHT_TOGGLE_DISABLED("command.admin.light_toggle_disabled"),
    COMMAND_ADMIN_INFO("command.admin.info"),
    COMMAND_ADMIN_CHAT_CLEARED("command.admin.chat_cleared"),
    COMMAND_ADMIN_TOP("command.admin.top"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS("command.admin.clean_protections"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS_START("command.admin.clean_protections_start"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS_CLEANING_UP("command.admin.clean_protections_cleaning_up"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS_END("command.admin.clean_protections_end"),
    COMMAND_ADMIN_CLEAN_OLD_PROTECTIONS_END("command.admin.clean_old_protections_end"),
    COMMAND_ADMIN_CLEAN_OLD_LOCATIONS_END("command.admin.clean_old_locations_end"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS_NONE("command.admin.clean_protections_none"),
    COMMAND_ADMIN_CLEAN_PROTECTIONS_PERCENTAGE("command.admin.clean_protections_percentage"),
    COMMAND_ADMIN_PING("command.admin.ping"),
    COMMAND_ADMIN_PING_OTHER("command.admin.ping_other"),
    COMMAND_ADMIN_PING_OTHER_NOT_FOUND("command.admin.ping_other_not_found"),
    COMMAND_ADMIN_INFO_VERSION("command.admin.info_version"),
    COMMAND_ADMIN_INFO_INTEGRATIONS_NONE("command.admin.info_integrations_none"),
    COMMAND_ADMIN_INFO_INTEGRATIONS_HEADER("command.admin.info_integrations_header"),
    COMMAND_ADMIN_INFO_INTEGRATIONS_ENTRY("command.admin.info_integrations_entry"),
    COMMAND_POSITION_INFO_1("command.position.info_1"),
    COMMAND_POSITION_INFO_2("command.position.info_2"),
    COMMAND_POSITION_INFO_3("command.position.info_3"),
    COMMAND_POSITION_NO_POSITIONS("command.position.no_positions"),
    COMMAND_POSITION_CLEAR("command.position.clear"),
    COMMAND_POSITION_SET_FIRST("command.position.set_first"),
    COMMAND_POSITION_SET_SECOND("command.position.set_second"),
    COMMAND_POSITION_REMOVE_FIRST("command.position.remove_first"),
    COMMAND_POSITION_REMOVE_SECOND("command.position.remove_second"),
    COMMAND_POSITION_INVALID_AMOUNT("command.position.invalid_amount"),
    COMMAND_POSITION_SHIFT("command.position.shift"),
    COMMAND_POSITION_NEED_BOTH_POSITIONS("command.position.need_both_positions"),
    COMMAND_POSITION_EXPAND("command.position.expand"),
    COMMAND_POSITION_DECREASE("command.position.decrease"),

    COMMAND_COOKIES("command.cookies"),
    COMMAND_COOKIES_PLAYER("command.cookies.player"),
    COMMAND_COOKIES_LORE_1("command.cookies.lore_1"),
    COMMAND_COOKIES_LORE_3("command.cookies.lore_3"),
    COMMAND_COOKIES_DISPLAYNAME("command.cookies.displayname");

    private final String key;
    MessageKey(String key) {
        this.key = key;
    }
}
