/**
 * Author:  rellu
 * Created: 19.02.2023
 */

CREATE TABLE IF NOT EXISTS `rellu_essentials`.`setting` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED` DATETIME NOT NULL,
  `CREATEDBY` INT NOT NULL,
  `UPDATED` DATETIME NULL,
  `UPDATEDBY` INT NULL,
  `DELETED` DATETIME NULL,
  `DELETEDBY` INT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`));