package de.relluem94.minecraft.server.spigot.essentials.enums;

public enum WorldSetting {
  NPC_BANKER,
  NPC_BAGSALESMAN,
  NPC_BEEKEEPER,
  NPC_ENCHANTER,
  ORE_RESPAWN,
  COLLECT_BAG,
  ENTITIES_DROP_COINS,
  ENTITIES_SPAWN_PHANTOM,
  DEATH_LOSE_COINS,
  DEATH_CREATE_HOME,
  DEATH_CHEST_SPAWN,
  SCOREBOARD_SHOW,
  USE_CLOUDSAILOR,
  PROTECTION_NOTIFY_SELF
}