package de.relluem94.minecraft.server.spigot.essentials.models;

import de.relluem94.minecraft.server.spigot.essentials.helpers.ItemHelper;
import de.relluem94.minecraft.server.spigot.essentials.models.pojo.NpcDialogueEntry;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.Data;
import org.json.JSONObject;

/**
 * Represents a non-player character managed by the RelluEssentials plugin. Holds persistent data such as database id,
 * profile name, inventory, world position, and orientation, as well as runtime data such as the spawned entity UUID,
 * the item helper, and the configured dialogue lines. Getters and setters for all fields are generated by Lombok.
 *
 * @author rellu
 */
@SuppressWarnings("checkstyle:GoogleNonConstantFieldName")
@Data
public class Npc {

  private final UUID id;
  private int dbid;
  private String profileName;
  private JSONObject inventory;
  private double x;
  private double y;
  private double z;
  private float yaw;
  private float pitch;
  private String worldName;
  private UUID entityUuid;
  private ItemHelper itemHelper;
  private List<NpcDialogueEntry> dialogueLines;

  /**
   * Creates an NPC without an inventory and with an empty list of dialogue lines.
   *
   * @param dbid        the database id of the NPC
   * @param id          the unique identifier of the NPC
   * @param profileName the name of the profile used for the NPC's appearance
   * @param x           the x coordinate of the NPC's location
   * @param y           the y coordinate of the NPC's location
   * @param z           the z coordinate of the NPC's location
   * @param yaw         the horizontal rotation of the NPC
   * @param pitch       the vertical rotation of the NPC
   * @param worldName   the name of the world in which the NPC is located
   */
  public Npc(int dbid, UUID id, String profileName, double x, double y, double z, float yaw, float pitch,
      String worldName) {
    this.dbid = dbid;
    this.id = id;
    this.profileName = profileName;
    this.x = x;
    this.y = y;
    this.z = z;
    this.yaw = yaw;
    this.pitch = pitch;

    this.worldName = worldName;
    this.dialogueLines = new ArrayList<>();
  }

  /**
   * Creates an NPC with the given inventory and with an empty list of dialogue lines.
   *
   * @param dbid        the database id of the NPC
   * @param id          the unique identifier of the NPC
   * @param profileName the name of the profile used for the NPC's appearance
   * @param inventory   the JSON representation of the NPC's inventory
   * @param x           the x coordinate of the NPC's location
   * @param y           the y coordinate of the NPC's location
   * @param z           the z coordinate of the NPC's location
   * @param yaw         the horizontal rotation of the NPC
   * @param pitch       the vertical rotation of the NPC
   * @param worldName   the name of the world in which the NPC is located
   */
  public Npc(int dbid, UUID id, String profileName, JSONObject inventory, double x, double y, double z, float yaw,
      float pitch, String worldName) {
    this(dbid, id, profileName, x, y, z, yaw, pitch, worldName);
    this.inventory = inventory;
  }
}