# yaml-language-server: $schema=https://raw.githubusercontent.com/codacy/codacy-analysis-cli/master/codacy-analysis-cli.yaml

engines:
  pmd:
    enabled: true
  checkstyle:
    enabled: true
  spotbugs:
    enabled: true
  checkov:
    enabled: false
  eslint:
    enabled: false
  stylelint:
    enabled: false
  scalastyle:
    enabled: false
  ameba:
    enabled: false
  credo:
    enabled: false
  remark-lint:
    enabled: false

ignore:
  - "target/**"